### ISSUE TITLE
Length src/js/working-with-arrays.md

### ISSUE THREAD

**Issue by SamAshcroft** [corndeladmin/tech-docs#20]
src/js/working-with-arrays.md
https://github.com/corndeladmin/tech-docs/blob/8d5f755b79ad9529e11e4ef4dbd0661658093d2c/src/js/working-with-arrays.md

**There are 10 items in the array, but the last item has an index of 9. Why? Remember that the first item has an index of 0.**

**Knowing this, we can use the length property to access the last item in the array**

Fallen into the "This" trap. Not sure what 'this' is. 

I think the point of length is that we don't need to know how many items there are, so it would be

**There are 10 items in the array, but the last item has an index of 9. Why? Remember that the first item has an index of 0.**

**Counting the items in large arrays will quickly get time-consuming. Instead, we can use the length property to access the last item in the array**

**Comment by nimonian** [comment]
Todo:
- [ ] Improve the explanation [here](https://swe-docs.netlify.app/js-video/arrays.html#array-length)
