### ISSUE TITLE
Console (Array Methods - Pop)

### ISSUE THREAD

**Issue by SamAshcroft** [corndeladmin/tech-docs#22]
In array methods Pop, we see

**console.log(resolutions) // ['Pick up knitting', 'Practice the violin more']**
**console.log(lastResolution) // 'Use a bullet journal'**

This is new code, would the learners know what console is and what console.log does?

(It's obvious based on the comments, but still might raise confusion and questions)

**Comment by nimonian** [comment]
This is improved by [the video explanation](https://swe-docs.netlify.app/js-video/array-push-pop.html)
