### ISSUE TITLE
Working with Arrays - Printing the Array

### ISSUE THREAD

**Issue by SamAshcroft** [corndeladmin/tech-docs#26]
**This will return the second, third and fourth items in the array:**

**;[
  'Practice the violin more',
  'Use a bullet journal',
  'Learn to fly a helicopter'
]**

Learners aren't shown how to print an array like this - please could you add that somewhere?

**Comment by nimonian** [comment]
This is updated [here](https://swe-docs.netlify.app/js-video/array-map.html#arrow-functions)
