### ISSUE TITLE
Transforming map

### ISSUE THREAD

**Issue by SamAshcroft** [corndeladmin/tech-docs#32]
This will return a new array containing all of the items from the original array, with an exclamation mark added to the end of each item:

Would be clearer as:

This will return a new array called **excitedResolutions** containing all of the items from the original array, with an exclamation mark added to the end of each item:

**Comment by nimonian** [comment]
I'm pretty confident that this is resolved by the explanation in the video - it's much clearer what is happening as the demonstration changes and logs things as it goes.
