### ISSUE TITLE
Exercise 2b tech docs - Transforming with Map

### ISSUE THREAD

**Issue by SamAshcroft** [corndeladmin/tech-docs#33]
It feels like a bit of a jump to go from this
![image](https://github.com/corndeladmin/tech-docs/assets/135987077/a82b4883-4c12-47c7-b399-654fb78514db)

To this
export function convertFilesizes(arr) {
  return arr.map(arr => arr/1000)
}

The learner would need to know that you can write this
const excitedResolutions = resolutions.map(resolution => resolution + '!')

...into a function, and use return to cut out this bit
const excitedResolutions =

Would the learner be familiar with converting between the tech doc example to the exercise answer?

**Comment by nimonian** [comment]
I'll leave this one open for a bit as there may be some discussion here.

Do you think the [new example](https://swe-docs.netlify.app/js-video/array-map.html#arrow-functions) is more similar to the exercise the learner is asked to complete? It now contains an arithmetic operation as the return value which may demystify the arrow function a bit, and is very similar to what the learner needs to do.

I also hope that the video adds more support in understanding how, when and why to write arrow functions.

**Comment by SamAshcroft** [comment]
It might help after this code -
const excitedResolutions = resolutions.map(resolution => resolution + '!')

...to say 
"Don't forget, you could also write the following if you want to get the output directly and return it within a function
return resolutions.map(resolution => resolution + '!')

This shows the learners directly the code rule they need to follow in the exercise
