### ISSUE TITLE
Exercise 2b transform mapping

### ISSUE THREAD

**Issue by SamAshcroft** [corndeladmin/tech-docs#34]
In the tech docs, is this code a bit of a red herring or deliberately required for exercise 2b?

function addExclamationMark(resolution) {
  return resolution + '!'
}

const excitedResolutions = resolutions.map(addExclamationMark)

learners could correctly do:
function remapThousand(arr) {
  return arr/1000
}
export function convertFilesizes(arr) {
  return arr.map(remapThousand)
}

But the above requires writing a function in - this might open a can of worms and the learners could then start writing in functions to solve other exercises. Do you want that?

The question is, do you want them writing the function version above, or the more simple
export function convertFilesizes(arr) {
  return arr.map(arr => arr/1000)
}

And should this be addressed somewhere?

**Comment by nimonian** [comment]
We've updated the examples to suggest that a named function might be appropriate for [more complex transformations](https://swe-docs.netlify.app/js-video/array-map.html#using-map) and an [arrow function](https://swe-docs.netlify.app/js-video/array-map.html#arrow-functions) as a convenient way of doing simpler maps.

Arrow functions are going to be added as the final topic in the pre-reading.
