### ISSUE TITLE
Different apostrophes

### ISSUE THREAD

**Issue by SamAshcroft** [corndeladmin/tech-docs#37]
**Please skip to final comment - I realise this is covered in Template Literals. The Formatting Numbers section just needs a slight addition**

In the tech docs especially string methods, there are different apostrophes. E.g.

const name = 'Ada Lovelace'

const formatString = `Hello, ${name}!`

Should they be this way?

**Comment by SamAshcroft** [comment]
*Better example
![image](https://github.com/corndeladmin/tech-docs/assets/135987077/cdd79ddd-2615-409f-a37f-ea62c361b1e9)

**Comment by SamAshcroft** [comment]
Turns out yes, using backtick apostrophes is important for JS (learning moment for me)

It's important that this is mentioned in the tech docs, otherwise learners can't complete exercise 3b

My answer was not working because it needed backticks
export function formatPrice(amount, currency) {
  return currency + '${amount.toFixed(2)}'
}

**Comment by SamAshcroft** [comment]
I realise that interpolating variables into strings is covered in Template Literals above the Formatting Numbers section, but I must have skipped or forgotten

The easy fix would be to turn this

This is useful for formatting currency.

js
const price = 4.9902573948

const formattedPrice = price.toFixed(2)

console.log(`£${formattedPrice}`) // '£4.99'

Into this

This is useful for formatting currency. **(Don't forget the important use of backticks! This is covered in the section "Template Literals" above).**

js
const price = 4.9902573948

const formattedPrice = price.toFixed(2)

console.log(`£${formattedPrice}`) // '£4.99'

**Comment by nimonian** [comment]
This is updated in the `js-videos` version of the course, which is likely to replace the `js` version soon.
