### ISSUE TITLE
Code box output 'undefined' (probably a known issue)

### ISSUE THREAD

**Issue by SamAshcroft** [corndeladmin/tech-docs#39]
The text says that the console shouldn't be used, so I assume that this is a known issue

The console outputs "undefined"
![image](https://github.com/corndeladmin/tech-docs/assets/135987077/01fcc999-98bd-4969-bb19-ff2fd7b22eb6)

**Comment by nimonian** [comment]
This is a wording issue! The names of the variables must be `a`, `b` and `c`.

I will improve the wording.
