### ISSUE TITLE
1.1 Orientation

### ISSUE THREAD

**Issue by AndrewYHuang** [corndeladmin/tech-docs#4]
To be completed _later_, once we have a good idea of what we'll need to introduce

**Comment by AndrewYHuang** [comment]
How to best use the documentation
- A good way to learn from it is to run the code examples and play around with them.

**Comment by nimonian** [comment]
How to clone a repo and open it in vscode

In particular, how to open a "folder" in vscode and how to "close the folder" without closing vscode

**Comment by nimonian** [comment]
Checking they can follow the "code, test, commit, push" workflow and are in the habit of doing regular small commits
